	<?php $this -> load -> view('resourcedb/header'); ?>

<link rel="stylesheet" href="assets/css/jquery.autocomplete.css"  />
<script type="text/javascript" src="assets/jquery/jquery-1.4.2.min.js" ></script>
<script type="text/javascript" src="assets/jquery/jquery.autocomplete.js" ></script>
<script type="text/javascript" >

// $function() used as  $(document).ready(function() has already been called in the header view
 $(function()
	{
		
	// disable the input field submit button for now
	$("#title_submit").attr("disabled", true);
	
		
	// Autocomplete plugin. The autofill option places the first selected title in the field.
	$("#resource_title").autocomplete('form/resource_autocomplete', 
		{
		multiple: false,
		multipleSeparator: ';', 
		autoFill: true
		});
		
	// In response to an event generated by input_box...
	$('input#resource_title').result(function(event, data, formatted) 
		{
			if (data)
			{
				//...set the hidden field value to the resource ID
				//alert(data);
				$("#resource_id").attr("value", data[1]);
				// Enable the submit button 
				$("#title_submit").attr("disabled", false);
			}
		}
		);

	
 }); // end function
 
</script>


    <?php
	# Get resource IDs and titles and shove them in a combo box
	
	?>
	<h1><?php echo $heading;?></h1>
	<p>You can pick a resource title to edit from the dropdown box below...</p>
	<!-- FORM -->
	<?php
	echo form_open('edit');
	# Go through query sent by controller to produce a combo box 
	foreach ($resource_query -> result() as $row)
	{
		$resource_ary[$row -> id] = $row -> title;
	}
	echo form_dropdown('resource_id', $resource_ary);
	echo form_submit('dropdown_submit', 'Submit');
	echo form_close();

	# Give user an auto-suggest field in case they prefer typing
	# to choosing from a combo box. Requires a bit of jQuery trickery 
	# to put the resource id into a hidden field
	# Use HTML to create input and hidden fields rather than HTML Helper method, as we need
	# the fields to have id attributes for the jQuery auto-suggest code
	?>
    <p>...or you can type part of the title in the field below:</p>
	<form method="post" action="edit" >
    <input type="text" id="resource_title" name="resource_title" size="40"  />
    <input type="hidden" id="resource_id" name="resource_id"  />	
    <input type="submit" id="title_submit" name="title_submit" value="Submit" />
    </form>
    <p>You can also use Browse and Search to find a resource, and as long as you're logged in as a contributor an edit option will be visible. </p>
	<?php
	
	?>    
<?php $this -> load -> view('resourcedb/footer'); ?>
