<script type="text/javascript" >

// $function() used as  $(document).ready(function() has already been called in the header view
 $(function()
	{
		
	// disable the input field submit button for now
	$("#title_submit").attr("disabled", true);
	
		
	// Autocomplete plugin. The autofill option places the first selected title in the field.
	$("#resource_title").autocomplete('resource/resource_autocomplete', 
		{
		multiple: false,
		multipleSeparator: ';', 
		autoFill: true
		});
		
	// In response to an event generated by input_box...
	$('input#resource_title').result(function(event, data, formatted) 
		{
			if (data)
			{
				//...set the hidden field value to the resource ID
				//alert(data);
				$("#resource_id").attr("value", data[1]);
				// Enable the submit button 
				$("#title_submit").attr("disabled", false);
			}
		}
		);

	
 }); // end function
 
</script>